config/routes.rb
Rails.application.routes.draw do

  get "/" => "items#index", as: :home
  resources :items
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  helper_method :sort_attribute, :sort_direction

  def index
    @items = Item.order(sort_attribute + ' ' + sort_direction)
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.update_attributes(completed: false)
    if @item.save
      flash[:notice] = "Task added successfully."
      redirect_to home_path
    else
      flash[:alert] = "There was a problem adding your task."
      redirect_to :back
    end
  end

  def update
    @item = Item.where(id: params[:id]).first
    @item.toggle(:completed)
    if @item.save
      if @item.completed == true
        flash[:notice] = "Task completed! Way to go!"
      elsif @item.completed == false
        flash[:notice] = "Task added back to list."
      end
      redirect_to home_path
    else
      flash[:alert] = "There was a problem updating the information."
      redirect_to :back
    end
  end

  def destroy
    @item = Item.where(id: params[:id]).first
    if @item && @item.destroy
      flash[:notice] = "Task deleted successfully."
      redirect_to home_path
    else
      flash[:alert] = "There was a problem deleting your task."
      redirect_to :back
    end
  end

  private
  def item_params
    params.require(:item).permit(:task, :completed)
  end

  def sort_attribute
    Item.column_names.include?(params[:sort]) ? params[:sort] : "completed"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(attribute, title = nil)
		title ||= attribute.titleize
		css_class = attribute == sort_attribute ? "current-sort #{sort_direction}" : "sort"
		direction = (attribute == sort_attribute && sort_direction == 'asc') ? 'desc' : 'asc'
		link_to title, {:sort => attribute, :direction => direction}, {:class => css_class}
	end 
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1 id='title'>To Do List</h1>
<div id='add-task-container'>
	<div class="form-container">
		<%= form_for @item do |f| %>
			<%=f.text_field :task, placeholder: 'Add a task', :maxlength => 30%>
			<br>
			<%=f.submit "Add to List", :class => "submit", data: {disable_with: "Submitting..."} %>
		<% end %>
	</div>
</div>
<div id='sort-options'>
	<%= sortable "task", "Sort by task name" %>
	<%= sortable "completed", "Sort by completion" %>
	<%= sortable "created_at", "Sort by date" %>
</div>
<div class='tasks-container'>
<% if @items.first %>
	<% @items.each do |item| %>
		<div class="task-container">
			<%= link_to item_path(item.id), method: :put do %>
				<% if item.completed == true %>
					<div class='checkbox checkbox-true'>
						<div class='check-line check-line-left'>
						</div>
						<div class='check-line check-line-right'>
						</div>
					</div>
				<% elsif item.completed == false %>
					<div class='checkbox checkbox-false'>
						<div class='check-line check-line-left'>
						</div>
						<div class='check-line check-line-right'>
						</div>
					</div>
				<% end %>
			<% end %>
			<div class='task-information'>
				<% if item.completed == true %>
					<div class='task task-true'>
						<span style='color:#21bea3;text-decoration:line-through'>
							<span style='color:#000'><%= item.task %></span>
						</span>
					</div>
				<% elsif item.completed == false %>
					<div class='task task-false'>
						<%= item.task %>
					</div>
				<% end %>
				<div class='created-at'>
					<%= item.created_at.strftime("%b %d, %Y, %l:%M %p") %>
				</div>
			</div>
			<%= link_to item_path(item.id), method: :delete, data: { confirm: "Are you sure you want to delete this task?" }, class: "delete-link" do %>
				<div class='checkbox delete-box'>
					<div class='check-line delete-line-left'>
					</div>
					<div class='check-line delete-line-right'>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
<% else %>
	You currently have no tasks to complete.
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UncubedToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class='page-container'>
		<div id='flash-container'>
			<% if flash[:notice] %>
				<div class="flash notice">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<% if flash[:alert] %>
				<div class="flash alert">
					<%= flash[:alert] %>
				</div>
			<% end %>
		</div>
		<%= yield %>
	</div>
</body>
</html>